# Generated by Django 5.2.4 on 2025-07-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='color',
            new_name='colour',
        ),
    ]
